name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Launch FastAPI server
        run: |
          source venv/bin/activate
          uvicorn main:app --host 0.0.0.0 --port 8080 --reload &   # start server in BG
          sleep 5  

          source venv/bin/activate
          python test_api.py    
