name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests uvicorn

      - name: Launch FastAPI server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8080 & 
          sleep 5

      - name: Run tests
        run: |
          python test_api.py
